# Generated by Django 3.1.14 on 2022-11-07 18:17

from django.db import migrations
import dynamicfields.models


class Migration(migrations.Migration):

    dependencies = [
        ('customers_legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalcustomerbankmodel',
            name='number',
        ),
        migrations.AlterField(
            model_name='customerlegaldynamicfieldcontentmodel',
            name='content',
            field=dynamicfields.models.DynamicField(blank=True, null=True),
        ),
    ]
