# Generated by Django 3.0.8 on 2020-07-23 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseaccount",
            name="birth_day",
            field=models.DateField(blank=True, default=None, null=True, verbose_name="birth day"),
        ),
        migrations.AddField(
            model_name="baseaccount",
            name="create_date",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Create date"),
            preserve_default=False,
        ),
        migrations.RunSQL(sql="update base_accounts set create_date = birth_day;"),
    ]
