# Generated by Django 3.0.8 on 2021-02-04 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_baseaccount_last_update_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='profiles_userprofile',
        ),
        migrations.AlterModelTable(
            name='userprofilelog',
            table='profiles_userprofilelog',
        ),
        migrations.CreateModel(
            name='ProfileAuthLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Auth time')),
                ('remote_ip', models.GenericIPAddressField(verbose_name='Remote ip', blank=True, null=True, default=None)),
                ('user_agent', models.CharField(max_length=256, verbose_name='Details')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
            options={
                'db_table': 'profiles_auth_log',
                'ordering': ('-id',),
            },
        ),
    ]
