UPDATE auth_permission SET name='Может добавлять права' WHERE codename='can_add_permission';
UPDATE auth_permission SET name='Может изменять права' WHERE codename='change_permission';
UPDATE auth_permission SET name='Может удалять права' WHERE codename='delete_permission';
UPDATE auth_permission SET name='Может видеть права' WHERE codename='view_permission';
UPDATE auth_permission SET name='Может добавлять группы' WHERE codename='add_group';
UPDATE auth_permission SET name='Может изменять группы' WHERE codename='change_group';
UPDATE auth_permission SET name='Может удалять группы' WHERE codename='delete_group';
UPDATE auth_permission SET name='Может видеть группы' WHERE codename='view_group';
UPDATE auth_permission SET name='Может добавлять типы объектов' WHERE codename='add_contenttype';
UPDATE auth_permission SET name='Может изменять типы объектов' WHERE codename='change_contenttype';
UPDATE auth_permission SET name='Может удалять типы объектов' WHERE codename='delete_contenttype';
UPDATE auth_permission SET name='Может видеть типы объектов' WHERE codename='view_contenttype';
UPDATE auth_permission SET name='Может добавлять сессии' WHERE codename='add_session';
UPDATE auth_permission SET name='Может изменять сессии' WHERE codename='change_session';
UPDATE auth_permission SET name='Может удалять сессии' WHERE codename='delete_session';
UPDATE auth_permission SET name='Может видеть сессии' WHERE codename='view_session';
UPDATE auth_permission SET name='Может добавлять токен' WHERE codename='add_token';
UPDATE auth_permission SET name='Может изменять токен' WHERE codename='change_token';
UPDATE auth_permission SET name='Может удалять токен' WHERE codename='delete_token';
UPDATE auth_permission SET name='Может видеть токен' WHERE codename='view_token';
UPDATE auth_permission SET name='Может добавлять группы' WHERE codename='add_group';
UPDATE auth_permission SET name='Может изменять группы' WHERE codename='change_group';
UPDATE auth_permission SET name='Может удалять группы' WHERE codename='delete_group';
UPDATE auth_permission SET name='Может видеть группы' WHERE codename='view_group';
UPDATE auth_permission SET name='Может добавлять учётки сотрудников' WHERE codename='add_userprofile';
UPDATE auth_permission SET name='Может изменять учётки сотрудников' WHERE codename='change_userprofile';
UPDATE auth_permission SET name='Может удалять учётки сотрудников' WHERE codename='delete_userprofile';
UPDATE auth_permission SET name='Может видеть учётки сотрудников' WHERE codename='view_userprofile';
UPDATE auth_permission SET name='Может добавлять периодические платежи' WHERE codename='add_periodicpay';
UPDATE auth_permission SET name='Может изменять периодические платежи' WHERE codename='change_periodicpay';
UPDATE auth_permission SET name='Может удалять периодические платежи' WHERE codename='delete_periodicpay';
UPDATE auth_permission SET name='Может видеть периодические платежи' WHERE codename='view_periodicpay';
UPDATE auth_permission SET name='Может добавлять услуги' WHERE codename='add_service';
UPDATE auth_permission SET name='Может изменять услуги' WHERE codename='change_service';
UPDATE auth_permission SET name='Может удалять услуги' WHERE codename='delete_service';
UPDATE auth_permission SET name='Может видеть услуги' WHERE codename='view_service';
UPDATE auth_permission SET name='Может добавлять серверы доступа' WHERE codename='add_gateway';
UPDATE auth_permission SET name='Может изменять серверы доступа' WHERE codename='change_gateway';
UPDATE auth_permission SET name='Может удалять серверы доступа' WHERE codename='delete_gateway';
UPDATE auth_permission SET name='Может видеть серверы доступа' WHERE codename='view_gateway';
UPDATE auth_permission SET name='Может добавлять устройства' WHERE codename='add_device';
UPDATE auth_permission SET name='Может изменять устройства' WHERE codename='change_device';
UPDATE auth_permission SET name='Может удалять устройства' WHERE codename='delete_device';
UPDATE auth_permission SET name='Может видеть устройства' WHERE codename='view_device';
UPDATE auth_permission SET name='Может добавлять порты устройств' WHERE codename='add_port';
UPDATE auth_permission SET name='Может изменять порты устройств' WHERE codename='change_port';
UPDATE auth_permission SET name='Может удалять порты устройств' WHERE codename='delete_port';
UPDATE auth_permission SET name='Может видеть порты устройств' WHERE codename='view_port';
UPDATE auth_permission SET name='Может включать/выключать порты' WHERE codename='can_toggle_ports';
UPDATE auth_permission SET name='Может добавлять абонентов' WHERE codename='add_customer';
UPDATE auth_permission SET name='Может изменять абонентов' WHERE codename='change_customer';
UPDATE auth_permission SET name='Может удалять абонентов' WHERE codename='delete_customer';
UPDATE auth_permission SET name='Может видеть абонентов' WHERE codename='view_customer';
UPDATE auth_permission SET name='Может покупать абоненту услугу' WHERE codename='can_buy_service';
UPDATE auth_permission SET name='Может пополнять абоненту счёт' WHERE codename='can_add_balance';
UPDATE auth_permission SET name='Может пинговать абонентов' WHERE codename='can_ping';
UPDATE auth_permission SET name='Может назначать периодический платёж' WHERE codename='add_periodicpayforid';
UPDATE auth_permission SET name='Может изменять периодический платёж' WHERE codename='change_periodicpayforid';
UPDATE auth_permission SET name='Может удалять периодический платёж' WHERE codename='delete_periodicpayforid';
UPDATE auth_permission SET name='Может видеть периодический платёж' WHERE codename='view_periodicpayforid';
UPDATE auth_permission SET name='Может добавлять паспортные данные' WHERE codename='add_passportinfo';
UPDATE auth_permission SET name='Может изменять паспортные данные' WHERE codename='change_passportinfo';
UPDATE auth_permission SET name='Может удалять паспортные данные' WHERE codename='delete_passportinfo';
UPDATE auth_permission SET name='Может видеть паспортные данные' WHERE codename='view_passportinfo';
UPDATE auth_permission SET name='Может добавлять долг для абонента' WHERE codename='add_invoiceforpayment';
UPDATE auth_permission SET name='Может изменять долг для абонента' WHERE codename='change_invoiceforpayment';
UPDATE auth_permission SET name='Может удалять долг для абонента' WHERE codename='delete_invoiceforpayment';
UPDATE auth_permission SET name='Может видеть долг для абонента' WHERE codename='view_invoiceforpayment';
UPDATE auth_permission SET name='Может добавлять улицы' WHERE codename='add_customerstreet';
UPDATE auth_permission SET name='Может изменять улицы' WHERE codename='change_customerstreet';
UPDATE auth_permission SET name='Может удалять улицы' WHERE codename='delete_customerstreet';
UPDATE auth_permission SET name='Может видеть улицы' WHERE codename='view_customerstreet';
UPDATE auth_permission SET name='Может добавлять услугу абонента' WHERE codename='add_customer service';
UPDATE auth_permission SET name='Может изменять услугу абонента' WHERE codename='change_customer service';
UPDATE auth_permission SET name='Может удалять услугу абонента' WHERE codename='delete_customer service';
UPDATE auth_permission SET name='Может видеть услугу абонента' WHERE codename='view_customer service';
UPDATE auth_permission SET name='Может завершать услугу абонента' WHERE codename='can_complete_service';
UPDATE auth_permission SET name='Может добавлять абонентский пароль' WHERE codename='add_customerrawpassword';
UPDATE auth_permission SET name='Может изменять абонентский пароль' WHERE codename='change_customerrawpassword';
UPDATE auth_permission SET name='Может удалять абонентский пароль' WHERE codename='delete_customerrawpassword';
UPDATE auth_permission SET name='Может видеть абонентский пароль' WHERE codename='view_customerrawpassword';
UPDATE auth_permission SET name='Может добавлять дополнительный номер телефона для абонента' WHERE codename='add_additionaltelephone';
UPDATE auth_permission SET name='Может изменять дополнительный номер телефона для абонента' WHERE codename='change_additionaltelephone';
UPDATE auth_permission SET name='Может удалять дополнительный номер телефона для абонента' WHERE codename='delete_additionaltelephone';
UPDATE auth_permission SET name='Может видеть дополнительные номера телефонов для абонентов' WHERE codename='view_additionaltelephone';
UPDATE auth_permission SET name='Может добавлять мессенджеры' WHERE codename='add_messenger';
UPDATE auth_permission SET name='Может изменять мессенджеры' WHERE codename='change_messenger';
UPDATE auth_permission SET name='Может удалять мессенджеры' WHERE codename='delete_messenger';
UPDATE auth_permission SET name='Может видеть мессенджеры' WHERE codename='view_messenger';
UPDATE auth_permission SET name='Может добавлять viber мессенджеры' WHERE codename='add_vibermessenger';
UPDATE auth_permission SET name='Может изменять viber мессенджеры' WHERE codename='change_vibermessenger';
UPDATE auth_permission SET name='Может удалять viber мессенджеры' WHERE codename='delete_vibermessenger';
UPDATE auth_permission SET name='Может видеть viber мессенджеры' WHERE codename='view_vibermessenger';
UPDATE auth_permission SET name='Может добавлять задачи' WHERE codename='add_task';
UPDATE auth_permission SET name='Может изменять задачи' WHERE codename='change_task';
UPDATE auth_permission SET name='Может удалять задачи' WHERE codename='delete_task';
UPDATE auth_permission SET name='Может видеть задачи' WHERE codename='view_task';
UPDATE auth_permission SET name='Имеет доступ ко всем задачам' WHERE codename='can_viewall';
UPDATE auth_permission SET name='Может напоминать о задачах их исполнителям' WHERE codename='can_remind';
UPDATE auth_permission SET name='Может комменировать задачи' WHERE codename='add_extracomment';
UPDATE auth_permission SET name='Может изменять комментарии к задачам' WHERE codename='change_extracomment';
UPDATE auth_permission SET name='Может удалять комментарии к задачам' WHERE codename='delete_extracomment';
UPDATE auth_permission SET name='Может видеть комментарии к задачам' WHERE codename='view_extracomment';
UPDATE auth_permission SET name='Может добавлять платёжный шлюз AllTime' WHERE codename='add_payalltimegateway';
UPDATE auth_permission SET name='Может изменять платёжный шлюз AllTime' WHERE codename='change_payalltimegateway';
UPDATE auth_permission SET name='Может удалять платёжный шлюз AllTime' WHERE codename='delete_payalltimegateway';
UPDATE auth_permission SET name='Может видеть платёжный шлюз AllTime' WHERE codename='view_payalltimegateway';
UPDATE auth_permission SET name='Может добавлять беседу' WHERE codename='add_conversation';
UPDATE auth_permission SET name='Может изменять беседу' WHERE codename='change_conversation';
UPDATE auth_permission SET name='Может удалять беседу' WHERE codename='delete_conversation';
UPDATE auth_permission SET name='Может видеть беседы' WHERE codename='view_conversation';
UPDATE auth_permission SET name='Может добавлять единоразовые платежи' WHERE codename='add_oneshotpay';
UPDATE auth_permission SET name='Может изменять единоразовые платежи' WHERE codename='change_oneshotpay';
UPDATE auth_permission SET name='Может удалять единоразовые платежи' WHERE codename='delete_oneshotpay';
UPDATE auth_permission SET name='Может видеть единоразовые платежи' WHERE codename='view_oneshotpay';
UPDATE auth_permission SET name='Может добавлять vlan' WHERE codename='add_vlanif';
UPDATE auth_permission SET name='Может изменять vlan' WHERE codename='change_vlanif';
UPDATE auth_permission SET name='Может удалять vlan' WHERE codename='delete_vlanif';
UPDATE auth_permission SET name='Может видеть vlan' WHERE codename='view_vlanif';
UPDATE auth_permission SET name='Может добавлять ip адрес' WHERE codename='add_customeripleasemodel';
UPDATE auth_permission SET name='Может изменять ip адрес' WHERE codename='change_customeripleasemodel';
UPDATE auth_permission SET name='Может удалять ip адрес' WHERE codename='delete_customeripleasemodel';
UPDATE auth_permission SET name='Может видеть ip адрес' WHERE codename='view_customeripleasemodel';
UPDATE auth_permission SET name='Может добавлять подсеть' WHERE codename='add_networkippool';
UPDATE auth_permission SET name='Может изменять подсеть' WHERE codename='change_networkippool';
UPDATE auth_permission SET name='Может удалять подсеть' WHERE codename='delete_networkippool';
UPDATE auth_permission SET name='Может видеть подсети' WHERE codename='view_networkippool';
UPDATE auth_permission SET name='Может добавлять приложения к задачам' WHERE codename='add_task document attachment';
UPDATE auth_permission SET name='Может изменять приложения к задачам' WHERE codename='change_task document attachment';
UPDATE auth_permission SET name='Может удалять приложения к задачам' WHERE codename='delete_task document attachment';
UPDATE auth_permission SET name='Может видеть приложения к задачам' WHERE codename='view_task document attachment';
UPDATE auth_permission SET name='Может добавлять приложения к абонентам' WHERE codename='add_customerattachment';
UPDATE auth_permission SET name='Может изменять приложения к абонентам' WHERE codename='change_customerattachment';
UPDATE auth_permission SET name='Может удалять приложения к абонентам' WHERE codename='delete_customerattachment';
UPDATE auth_permission SET name='Может видеть приложения к абонентам' WHERE codename='view_customerattachment';
UPDATE auth_permission SET name='Может добавлять логи' WHERE codename='add_logentry';
UPDATE auth_permission SET name='Может добавлять логи' WHERE codename='change_logentry';
UPDATE auth_permission SET name='Может удалять логи' WHERE codename='delete_logentry';
UPDATE auth_permission SET name='Может видеть логи' WHERE codename='view_logentry';
UPDATE auth_permission SET name='Может удалять ONU с OLT' WHERE codename='can_remove_from_olt';
UPDATE auth_permission SET name='Может пользоваться кнопкой "Исправить"' WHERE codename='can_fix_onu';
UPDATE auth_permission SET name='Может применять конфиг для устройств с билинга' WHERE codename='can_apply_onu_config';
