# Generated by Django 3.0.8 on 2021-01-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_additionaltelephone_create_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="passportinfo",
            name="division_code",
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="Division code"),
        ),
    ]
