# Generated by Django 3.1.12 on 2021-07-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_change_find_customer_service_by_device_credentials_fn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ("fio",),
                "permissions": [
                    ("can_buy_service", "Buy service perm"),
                    ("can_add_balance", "fill account"),
                    ("can_add_negative_balance", "Fill account balance on negative cost"),
                    ("can_ping", "Can ping"),
                    ("can_complete_service", "Can complete service"),
                ],
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
            },
        ),
    ]
