# Generated by Django 3.1.12 on 2021-07-21 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0009_new_balance_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={
                'ordering': ('fio',),
                'permissions': [
                    ('can_buy_service', 'Buy service perm'),
                    ('can_add_balance', 'fill account'),
                    ('can_add_negative_balance', 'Fill account balance on negative cost'),
                    ('can_ping', 'Can ping'),
                    ('can_complete_service', 'Can complete service'),
                    ('can_view_activity_report', 'Can view activity_report'),
                    ('can_view_service_type_report', 'Can view service type report')
                ],
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers'
            },
        ),
    ]
