# Generated by Django 3.1.12 on 2021-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20210721_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlog',
            name='from_balance',
            field=models.FloatField(default=0, verbose_name='From balance'),
        ),
        migrations.AddField(
            model_name='customerlog',
            name='to_balance',
            field=models.FloatField(default=0, verbose_name='To balance'),
        ),
    ]
