# Generated by Django 3.1.12 on 2021-08-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_auto_20210801_1300'),
        ("networks", "0003_radius_integration"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=[],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ip_address',
        ),
    ]
