# Generated by Django 3.1.12 on 2021-09-06 13:04

from django.db import migrations, models
import django.db.models.deletion
from dynamicfields.models import DynamicField


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfields', '0001_initial'),
        ('customers', '0012_auto_20210803_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDynamicFieldContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', DynamicField(blank=True, max_length=512, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_contents', to='dynamicfields.fieldmodel')),
            ],
            options={
                'db_table': 'dynamic_field_content',
            },
        ),
    ]
