# Generated by Django 3.1.12 on 2021-09-09 16:54

from django.db import migrations

from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customerdynamicfieldcontentmodel'),
    ]

    operations = [
        migrations.RunSQL(
            sql=read_all_file("0014_fetch_customers_by_not_activity_sql_procedure.sql", __file__),
            reverse_sql="DROP FUNCTION IF EXISTS fetch_customers_by_not_activity"
                        "(date_limit timestamptz, out_limit integer);"
        )
    ]
