# Generated by Django 3.1.12 on 2021-09-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('customers', '0014_fetch_customers_by_not_activity_sql_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.deletion.SET_NULL,
                                    to='addresses.addressmodel'),
        ),
        migrations.RunSQL(
            # Attach customers to address streets
            sql=(
                "UPDATE customers SET address_id = adrs.id "
                "from addresses adrs "
                "left join customer_street cs on group_id = adrs.parent_addr_id "
                "WHERE adrs.parent_addr_id = customers.group_id "
                "  AND adrs.title = cs.name "
                "  AND adrs.address_type = 8;"
            )
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street'
        )
    ]
