# Generated by Django 3.1.13 on 2021-11-09 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfields', '0003_auto_20211109_1637'),
        ('customers', '0015_change_street'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerdynamicfieldcontentmodel',
            unique_together={('customer', 'field')},
        ),
    ]
