# Generated by Django 3.1.13 on 2021-12-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20211028_1430'),
        ('customers', '0016_auto_20211109_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportinfo',
            name='registration_address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.addressmodel'),
        ),
    ]
