# Generated by Django 3.1.13 on 2022-01-20 17:04

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_passportinfo_registration_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='house',
        ),
        migrations.AlterField(
            model_name='customer',
            name='markers',
            field=bitfield.models.BitField((('icon_donkey', 'Donkey'), ('icon_fire', 'Fire'), ('icon_ok', 'Ok'), ('icon_king', 'King'), ('icon_tv', 'TV'), ('icon_smile', 'Smile'), ('icon_dollar', 'Dollar'), ('icon_service', 'Service'), ('icon_mrk', 'Marker'), ('icon_red_tel', 'Red phone'), ('icon_green_tel', 'Green phone'), ('icon_doc', 'Document')), default=0),
        ),
        migrations.AlterField(
            model_name='passportinfo',
            name='distributor',
            field=models.CharField(max_length=512, verbose_name='Distributor'),
        ),
        migrations.DeleteModel(
            name='CustomerStreet',
        ),
    ]
