# Generated by Django 3.1.14 on 2022-11-07 18:09

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_auto_20220804_1203'),
        ('services', '0007_auto_20221107_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('can_buy_service', 'Buy service perm'), ('can_add_balance', 'fill account'), ('can_add_negative_balance', 'Fill account balance on negative cost'), ('can_ping', 'Can ping'), ('can_complete_service', 'Can complete service')], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='current_service',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_connected_service',
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='customer',
            name='markers',
            field=bitfield.models.BitField((('icon_donkey', 'Donkey'), ('icon_fire', 'Fire'), ('icon_ok', 'Ok'), ('icon_king', 'King'), ('icon_tv', 'TV'), ('icon_smile', 'Smile'), ('icon_dollar', 'Dollar'), ('icon_service', 'Service'), ('icon_mrk', 'Marker'), ('icon_red_tel', 'Red phone'), ('icon_green_tel', 'Green phone'), ('icon_doc', 'Document'), ('icon_reddoc', 'Red document')), default=0),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CustomerService',
                )
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='periodicpayforid',
                    name='account',
                ),
                migrations.RemoveField(
                    model_name='periodicpayforid',
                    name='periodic_pay',
                ),
                migrations.DeleteModel(
                    name='PeriodicPayForId',
                ),
            ]
        ),
    ]
