# Generated by Django 2.2.3 on 2019-07-19 00:27

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency("profiles.UserProfile"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("descr", models.CharField(blank=True, max_length=128, null=True, verbose_name="Description")),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Low"), (1, "Average"), (2, "Higher")], default=0, verbose_name="A priority"
                    ),
                ),
                (
                    "out_date",
                    models.DateField(
                        blank=True, default=tasks.models.delta_add_days, null=True, verbose_name="Reality"
                    ),
                ),
                ("time_of_create", models.DateTimeField(auto_now_add=True, verbose_name="Date of create")),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "New"), (1, "Confused"), (2, "Completed")], default=0, verbose_name="Condition"
                    ),
                ),
                (
                    "mode",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "not chosen"),
                            (1, "ip conflict"),
                            (2, "yellow triangle"),
                            (3, "red cross"),
                            (4, "weak speed"),
                            (5, "cable break"),
                            (6, "connection"),
                            (7, "periodic disappearance"),
                            (8, "router setup"),
                            (9, "configure onu"),
                            (10, "crimp cable"),
                            (11, "Internet crash"),
                            (12, "other"),
                        ],
                        default=0,
                        verbose_name="The nature of the damage",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="profiles.UserProfile",
                        verbose_name="Task author",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="customers.Customer", verbose_name="Customer"
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="them_task", to="profiles.UserProfile", verbose_name="Recipients"
                    ),
                ),
            ],
            options={
                "db_table": "task",
                "ordering": ("-id",),
                "permissions": (("can_viewall", "Access to all tasks"), ("can_remind", "Reminders of tasks")),
            },
        ),
        migrations.CreateModel(
            name="ExtraComment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Text of comment")),
                ("date_create", models.DateTimeField(auto_now_add=True, verbose_name="Time of create")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="profiles.UserProfile", verbose_name="Author"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.Task", verbose_name="Task"
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra comment",
                "verbose_name_plural": "Extra comments",
                "db_table": "task_extra_comments",
                "ordering": ("-date_create",),
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "act_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Change task"),
                            (2, "Create task"),
                            (3, "Delete task"),
                            (4, "Completing tasks"),
                            (5, "The task failed"),
                        ]
                    ),
                ),
                ("when", models.DateTimeField(auto_now_add=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.Task")),
                (
                    "who",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="profiles.UserProfile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Change log",
                "verbose_name_plural": "Change logs",
                "db_table": "task_change_log",
                "ordering": ("-when",),
            },
        ),
    ]
