# Generated by Django 2.2.10 on 2020-04-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="state",
            new_name="task_state",
        ),
    ]
