# Generated by Django 3.0.8 on 2020-10-14 19:11

from django.db import migrations, models
from django.db.models.deletion import CASCADE


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("tasks", "0003_taskdocumentattachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("-id",), "permissions": [("can_remind", "Reminders of tasks")]},
        ),
        migrations.AddField(
            model_name="task",
            name="site",
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=CASCADE, to="sites.Site"),
        ),
    ]
