# Generated by Django 3.1.7 on 2021-04-20 00:17

from django.db import migrations, models
import django.db.models.deletion
import djing2.models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_auto_20210204_2043"),
        ("tasks", "0004_auto_20201014_1911"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStateChangeLogModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state_data", models.JSONField(verbose_name="State change data")),
                ("when", models.DateTimeField(auto_now_add=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.task")),
                (
                    "who",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="profiles.userprofile"
                    ),
                ),
            ],
            options={
                "verbose_name": "Change log",
                "verbose_name_plural": "Change logs",
                "db_table": "task_state_change_log",
                "ordering": ("-id",),
            },
            bases=(djing2.models.BaseAbstractModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name="ChangeLog",
        ),
    ]
