# Generated by Django 3.1.12 on 2021-07-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210420_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={
                'ordering': ('-id',),
                'permissions': [
                    ('can_remind', 'Reminders of tasks'),
                    ('can_view_task_mode_report', 'Can view task mode report')
                ]
            },
        ),
    ]
