# Generated by Django 3.1.14 on 2022-03-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210204_2043'),
        ('tasks', '0006_auto_20210721_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
            ],
            options={
                'db_table': 'task_modes',
            },
        ),
        migrations.AlterModelOptions(
            name='extracomment',
            options={'verbose_name': 'Extra comment', 'verbose_name_plural': 'Extra comments'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_remind', 'Reminders of tasks'), ('can_view_task_mode_report', 'Can view task mode report')]},
        ),
        migrations.AlterModelOptions(
            name='taskstatechangelogmodel',
            options={'verbose_name': 'Change log', 'verbose_name_plural': 'Change logs'},
        ),
        migrations.CreateModel(
            name='TaskFinishDocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Document code')),
                ('act_num', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Act num')),
                ('create_time', models.DateTimeField(verbose_name='Time of create')),
                ('finish_date', models.DateTimeField(verbose_name='Finish time')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Author')),
                ('recipients', models.ManyToManyField(related_name='finish_docs', to='profiles.UserProfile', verbose_name='Recipients')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Task')),
                ('task_mode', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tasks.taskmodemodel', verbose_name='Mode')),
            ],
            options={
                'db_table': 'task_finish_docs',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_mode',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tasks.taskmodemodel', verbose_name='Mode'),
        ),
    ]
