# Generated by Django 3.1.14 on 2022-10-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20220316_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='mode',
        ),
    ]
