# Generated by Django 3.1.14 on 2022-11-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_remind', 'Reminders of tasks'), ('can_view_task_mode_report', 'Can view task mode report'), ('can_finish_task', 'Can finish tasks'), ('can_fail_task', 'Can mark task as failed'), ('can_view_reports', 'Can view reports')]},
        ),
    ]
