# Generated by Django 3.1.12 on 2021-07-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0008_auto_20210305_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Map point title')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='map_attachments/%Y_%m_%d', verbose_name='Attachment')),
                ('devices', models.ManyToManyField(db_table='dot_device', to='devices.Device', verbose_name='Devices')),
            ],
            options={
                'verbose_name': 'Map point',
                'verbose_name_plural': 'Map points',
                'db_table': 'maps_dots',
                'ordering': ('title',),
            },
        ),
    ]
