version: '3.5'
services:
  postgres:
    hostname: postgres
    image: postgres:13.4-alpine
    user: postgres
    working_dir: /var/lib/postgresql
    secrets:
      - POSTGRES_PASSWORD
    stop_grace_period: 1m
    ports:
      - 5432:5432
    stdin_open: true
    tty: true
    restart: on-failure
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_HOST
    #networks: app_net_backend
  app:
    build:
      context: .
    container_name: djing2_app_dev
    hostname: app
    depends_on:
      - postgres
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    secrets:
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - VAPID_PUBLIC_KEY
      - VAPID_PRIVATE_KEY
      - FIELD_ENCRYPTION_KEY
      - API_AUTH_SECRET
      - RADIUS_SECRET
      - SORM_EXPORT_FTP_PASSWORD
    environment:
      - PORT=8000
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - APP_DEBUG
      - RADIUS_APP_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_HOST
      - API_AUTH_SUBNET
      - MESSENGER_BOT_PUBLIC_URL
      - ARPING_COMMAND
      - ARPING_ENABLED
      - SORM_EXPORT_FTP_HOST
      - SORM_EXPORT_FTP_USERNAME
      - SORM_EXPORT_FTP_DISABLE
      - ALLOWED_HOSTS
      - SECRETS_DIR_PATH
      - CUSTOMERS_PASSPORT_DEFAULT_DISTRIBUTOR
    volumes:
      - .:/var/www/djing2
      - media-data:/var/www/djing2/media
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime
      - ~/.gitconfig:/root/.gitconfig
    #networks: app_net_backend

#   ui:
#     build: djing2-ui/
#     stop_grace_period: 1m
#     user: node
#     ports:
#       - 8080:8080
#     stdin_open: true
#     tty: true
#     volumes:
#       - ../../djing2-elui:/home/node/app
#       - /tmp:/tmp
#       - /etc/localtime:/etc/localtime

#  ws:
#    build: ws/
#    ports:
#      - 3211:3211
#    djing2freeradius:
#    build: djing2freeradius/
#    depends_on:
#      - app
#    ports:
#      - 1812:1812
#      - 1813:1813
#      - 67:67
#    secrets:
#      - RADIUS_SECRET
volumes:
  media-data:
  postgresql-data:

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  DJANGO_SECRET_KEY:
    file: ./secrets/DJANGO_SECRET_KEY
  API_AUTH_SECRET:
    file: ./secrets/API_AUTH_SECRET
  FIELD_ENCRYPTION_KEY:
    file: ./secrets/FIELD_ENCRYPTION_KEY
  VAPID_PUBLIC_KEY:
    file: ./secrets/VAPID_PUBLIC_KEY
  VAPID_PRIVATE_KEY:
    file: ./secrets/VAPID_PRIVATE_KEY
  RADIUS_SECRET:
    file: ./secrets/RADIUS_SECRET
  SORM_EXPORT_FTP_PASSWORD:
    file: ./secrets/SORM_EXPORT_FTP_PASSWORD

#networks:
#  app_net_frontend:
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
#    ipam:
#      driver: default
#      config:
#      - subnet: 172.16.238.0/24
#  app_net_backend:
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
#    internal: true
#    ipam:
#      driver: default
#      config:
#      - subnet: 172.16.239.0/24
