version: '3.5'
services:
  nginx:
    container_name: djing2_web
    hostname: djing2_web
    build:
      context: docker/djing2_nginx/
      dockerfile: Dockerfile_release
    depends_on:
      - app
    ports:
      - 80:80
    environment:
      - NGINX_SERVER_NAME=localhost
    volumes:
      - media-data:/media
      - nginx_logs:/var/log/nginx
      - /etc/localtime:/etc/localtime
    #networks: app_net_frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/"]
      interval: 120s
      timeout: 10s
      retries: 3
      start_period: 30s
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:13.4-alpine
    user: postgres
    working_dir: /var/lib/postgresql
    secrets:
      - POSTGRES_PASSWORD
    stop_grace_period: 1m
    ports:
      - 5432:5432
    stdin_open: true
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_HOST
    #networks: app_net_backend
  ws:
    build: docker/ws/
    ports:
      - 3211:3211
  app:
    build:
      context: .
      dockerfile: Dockerfile_release
    container_name: djing2_app_prod
    depends_on:
      - postgres
    restart: always
    ports:
      - 3031:3031
    stdin_open: true
    tty: true
    secrets:
      - POSTGRES_PASSWORD
      - DJANGO_SECRET_KEY
      - VAPID_PUBLIC_KEY
      - VAPID_PRIVATE_KEY
      - FIELD_ENCRYPTION_KEY
      - API_AUTH_SECRET
      - RADIUS_SECRET
      - SORM_EXPORT_FTP_PASSWORD
    environment:
      - PORT=8000
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - APP_DEBUG
      - RADIUS_APP_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_HOST
      - API_AUTH_SUBNET
      - MESSENGER_BOT_PUBLIC_URL
      - ARPING_COMMAND
      - ARPING_ENABLED
      - SORM_EXPORT_FTP_HOST
      - SORM_EXPORT_FTP_USERNAME
      - SORM_EXPORT_FTP_DISABLE
      - ALLOWED_HOSTS
      - SECRETS_DIR_PATH
      - CUSTOMERS_PASSPORT_DEFAULT_DISTRIBUTOR
    volumes:
      - media-data:/var/www/djing2/media
      - /etc/localtime:/etc/localtime
    #networks: app_net_backend
#  djing2freeradius:
#    image: djing2freeradius
#    build:
#      context: djing2freeradius
#    depends_on:
#      - nginx
#    container_name: djing2freeradius
#    hostname: djing2freeradius
#    ports:
#      - 1812:1812
#      - 1813:1813
#      - 67:67
#    secrets:
#      - RADIUS_SECRET

volumes:
  postgresql-data:
  media-data:
  nginx_logs:

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD
  DJANGO_SECRET_KEY:
    file: ./secrets/DJANGO_SECRET_KEY
  API_AUTH_SECRET:
    file: ./secrets/API_AUTH_SECRET
  FIELD_ENCRYPTION_KEY:
    file: ./secrets/FIELD_ENCRYPTION_KEY
  VAPID_PUBLIC_KEY:
    file: ./secrets/VAPID_PUBLIC_KEY
  VAPID_PRIVATE_KEY:
    file: ./secrets/VAPID_PRIVATE_KEY
  RADIUS_SECRET:
    file: ./secrets/RADIUS_SECRET
  SORM_EXPORT_FTP_PASSWORD:
    file: ./secrets/SORM_EXPORT_FTP_PASSWORD


#networks:
#  app_net_frontend:
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
#    ipam:
#      driver: default
#      config:
#      - subnet: 172.16.238.0/24
#  app_net_backend:
#    driver: bridge
#    driver_opts:
#      com.docker.network.enable_ipv6: "false"
#    internal: true
#    ipam:
#      driver: default
#      config:
#      - subnet: 172.16.239.0/24
