# Generated by Django 2.2.2 on 2019-06-30 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=127, unique=True, verbose_name="Title")),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        null=True,
                        default=None,
                        max_length=12,
                        validators=[django.core.validators.RegexValidator("^\\w{1,127}$")],
                        verbose_name="Tech code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "db_table": "groups",
                "ordering": ("title",),
            },
        ),
    ]
