# Generated by Django 3.1.14 on 2022-11-07 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0002_group_sites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='code',
        ),
    ]
