# Generated by Django 2.2.5 on 2019-12-18 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0002_auto_20191218_1907'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'permissions': (('can_toggle_ports', 'Can toggle ports'),), 'verbose_name': 'Port', 'verbose_name_plural': 'Ports'},
        ),
        migrations.AddField(
            model_name='port',
            name='operating_mode',
            field=models.PositiveSmallIntegerField(choices=[
                (0, 'Not chosen'), (1, 'Access'), (2, 'Trunk'),
                (3, 'Hybrid'), (4, 'General')
            ], default=0, verbose_name='Operating mode'),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_type',
            field=models.PositiveSmallIntegerField(choices=[
                (0, 'Unknown Device'), (1, 'DLink switch'), (2, 'PON OLT'),
                (3, 'PON ONU BDCOM'), (4, 'Eltex switch'), (5, 'OLT ZTE C320'),
                (6, 'Zte ONU F660'), (7, 'Zte ONU F601'), (8, 'Huawei switch')
            ], default=0, verbose_name='Device type'),
        ),
        migrations.CreateModel(
            name='PortVlanMemberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.PositiveSmallIntegerField(choices=[
                    (0, 'Not chosen'), (1, 'Default'), (2, 'Untagged'),
                    (3, 'Tagged'), (4, 'Hybrid')
                ], default=0, verbose_name='Operating mode')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Port')),
                ('vlanif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.VlanIf')),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='vlans',
            field=models.ManyToManyField(through='devices.PortVlanMemberModel', to='networks.VlanIf', verbose_name='VLan list'),
        ),
    ]
