# Generated by Django 2.2.4 on 2020-01-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20191218_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('id',), 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ('num',), 'permissions': (('can_toggle_ports', 'Can toggle ports'),), 'verbose_name': 'Port', 'verbose_name_plural': 'Ports'},
        ),
        migrations.AddField(
            model_name='device',
            name='vlans',
            field=models.ManyToManyField(to='networks.VlanIf', verbose_name='Available vlans', blank=True),
        )
    ]
