# Generated by Django 2.2.9 on 2020-03-25 16:42

from django.db import migrations
from devices.device_config import DEVICE_TYPES


create_tbl = """CREATE TABLE "device_dev_type_is_use_dev_port"
(
  "id"              serial  NOT NULL PRIMARY KEY,
  "dev_type"        integer NOT NULL,
  "is_use_dev_port" boolean NOT NULL
);
ALTER TABLE "device_dev_type_is_use_dev_port"
  ADD CONSTRAINT "device_dev_type_is_use_dev_port_type_is_use" UNIQUE ("dev_type", "is_use_dev_port");"""


def _prepare_sql_inject():
    vals = ', '.join("(%d, %s)" % (num, klass.get_is_use_device_port()) for num, klass in DEVICE_TYPES).lower()
    return 'INSERT INTO "device_dev_type_is_use_dev_port" (dev_type, is_use_dev_port) VALUES %s;' % vals


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0003_auto_20200104_1509'),
    ]

    operations = [
        migrations.RunSQL(sql=create_tbl),
        migrations.RunSQL(sql=_prepare_sql_inject())
    ]
