# Generated by Django 3.0.8 on 2020-08-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_push_dev_type2db'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.CharField(blank=True, choices=[('zte_f660_router', 'Zte F660 router')], default=None, max_length=64, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown Device'), (1, 'DLink DGS-1100-10/ME'), (2, 'PON OLT'), (3, 'PON ONU BDCOM'), (4, 'Eltex switch'), (5, 'OLT ZTE C320'), (6, 'Zte ONU F660'), (7, 'Zte ONU F601'), (8, 'Huawei switch'), (9, 'DLink DGS-3120-24SC'), (10, 'DLink DGS-1100-06/ME'), (11, 'DLink DGS-3627G')], default=0, verbose_name='Device type'),
        ),
        migrations.RunSQL(sql="UPDATE device SET code='zte_f660_bridge' WHERE dev_type=12"),
        migrations.RunSQL(sql="UPDATE device SET code='zte_f660_router' WHERE dev_type=6"),
        migrations.RunSQL(sql="UPDATE device SET code='zte_f601_bridge' WHERE dev_type=7"),
        migrations.RunSQL(sql="UPDATE device SET dev_type=6 WHERE dev_type=12"),
    ]
