# Generated by Django 3.0.8 on 2021-01-18 15:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupapp', '0002_group_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportStampModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Action time')),
                ('last_attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Last attempt time')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Attempt count')),
                ('export_status', models.PositiveIntegerField(choices=[(0, 'Not exported'), (1, 'Successful'), (2, 'Failed')], default=0, verbose_name='Export status')),
                ('export_type', models.IntegerField(choices=[(0, 'Unknown Choice'), (1, 'Customer Root'), (2, 'Customer Contract'), (3, 'Customer Address'), (4, 'Customer Ap Address'), (5, 'Customer Individual'), (6, 'Customer Legal'), (7, 'Customer Contact'), (8, 'Network Static Ip'), (9, 'Payment Unknown'), (10, 'Service Nomenclature'), (11, 'Service Customer'), (12, 'Service Customer Manual')], default=0, verbose_name='Export type')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Export event data')),
            ],
            options={
                'db_table': 'sorm_export_stamp',
            },
        ),
        migrations.CreateModel(
            name='FIASAddressLevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='FIAS address level')),
                ('num', models.IntegerField(verbose_name='Level num')),
            ],
            options={
                'db_table': 'sorm_addr_levels',
            },
        ),
        migrations.CreateModel(
            name='FIASAddressTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Address type num')),
                ('name', models.CharField(max_length=16)),
                ('full_name', models.CharField(max_length=128)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorm_export.FIASAddressLevelModel')),
            ],
            options={
                'db_table': 'sorm_addr_types',
            },
        ),
        migrations.CreateModel(
            name='FiasCountryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Country')),
                ('ao_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorm_export.FIASAddressTypeModel')),
            ],
            options={
                'db_table': 'sorm_countries',
            },
        ),
        migrations.CreateModel(
            name='FiasRegionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Country')),
                ('ao_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorm_export.FIASAddressTypeModel')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorm_export.FiasCountryModel')),
            ],
            options={
                'db_table': 'sorm_regions',
            },
        ),
        migrations.CreateModel(
            name='GroupFIASInfoModel',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='groupapp.Group')),
                ('ao_type', models.ForeignKey(help_text='соответствует полю SOCRBASE.KOD_T_ST', on_delete=django.db.models.deletion.CASCADE, to='sorm_export.FIASAddressTypeModel')),
                ('region', models.ForeignKey(help_text='соответствует полю SOCRBASE.SOCRNAME', on_delete=django.db.models.deletion.CASCADE, to='sorm_export.FiasRegionModel', verbose_name='Region type')),
            ],
        ),
    ]
