# Generated by Django 3.0.8 on 2021-01-08 14:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportStampModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Action time')),
                ('last_attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Last attempt time')),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Attempt count')),
                ('export_status', models.PositiveIntegerField(choices=[(0, 'Not exported'), (1, 'Successful'), (2, 'Failed')], default=0, verbose_name='Export status')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Export event data')),
            ],
            options={
                'db_table': 'sorm_export_stamp',
            },
        ),
    ]
