# Generated by Django 3.0.8 on 2020-12-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_auto_20201014_1859"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Create time"),
        ),
    ]
