# Generated by Django 3.1.14 on 2022-10-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traf_stat', '0002_auto_20210110_2006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trafficcache',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trafficcache',
            name='customer',
        ),
        migrations.DeleteModel(
            name='TrafficArchiveModel',
        ),
        migrations.DeleteModel(
            name='TrafficCache',
        ),
        migrations.RunSQL("DROP FUNCTION traffic_prepare_customer_id_by_ip() CASCADE;"),
        migrations.RunSQL("DROP FUNCTION traffic_copy_stat2archive() CASCADE;"),
        migrations.RunSQL("DROP FUNCTION create_traf_archive_partition_tbl(timestamp) CASCADE;"),
        migrations.RunSQL("DROP FUNCTION traffic_copy_stat2partition_from_traf_archive() CASCADE"),
        migrations.RunSQL("DROP TYPE TrafFetchArchiveReturnType CASCADE;"),
        migrations.RunSQL("DROP FUNCTION if exists traf_fetch_archive4graph() CASCADE")
    ]
