# Generated by Django 3.0.8 on 2021-02-19 20:55

from django.db import migrations, models

from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('radiusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='radius_username',
            field=models.CharField(max_length=128, verbose_name='User-Name av pair from radius'),
        ),
        migrations.RunSQL(
            sql=read_all_file('0002_auto_20210219_2055.sql', __file__)
        )
    ]
