# Generated by Django 3.0.8 on 2021-02-18 11:23

from django.db import migrations

from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('radiusapp', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql=read_all_file('0002_dhcp_assign_logic.sql', __file__))
    ]
