# Generated by Django 3.0.8 on 2021-02-22 12:37

from django.db import migrations, models
from django.db.models.deletion import CASCADE
from djing2.lib.for_migrations import read_all_file


def create_default_vlan(apps, schema_editor):
    VlanIf = apps.get_model('networks', 'VlanIf')
    vlan1 = VlanIf.objects.filter(vid=1)
    if not vlan1.exists():
        VlanIf.objects.create(
            title='default',
            vid=1
        )


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0014_update_find_new_ip_pool_lease_fn'),
        ('customers', '0007_passportinfo_division_code'),
        ('radiusapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRadiusSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_time', models.DateTimeField(auto_now_add=True, help_text='Time when session assigned first time')),
                ('last_event_time', models.DateTimeField(verbose_name='Last update time')),
                ('radius_username', models.CharField(max_length=128, verbose_name='User-Name av pair from radius')),
                ('session_id', models.UUIDField(verbose_name='Unique session id')),
                ('session_duration', models.DurationField(blank=True, default=None, null=True, verbose_name='most often this is Acct-Session-Time av pair')),
                ('input_octets', models.BigIntegerField(default=0)),
                ('output_octets', models.BigIntegerField(default=0)),
                ('input_packets', models.BigIntegerField(default=0)),
                ('output_packets', models.BigIntegerField(default=0)),
                ('closed', models.BooleanField(default=False, verbose_name='Is session finished')),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=CASCADE, to='customers.Customer')),
                ('ip_lease', models.OneToOneField(on_delete=CASCADE, to='networks.CustomerIpLeaseModel', verbose_name='Ip lease')),
            ],
            options={
                'db_table': 'radius_customer_session',
            },
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.RunSQL(
            sql=read_all_file('0002_auto_20210219_2055.sql', __file__)
        ),
        migrations.RunPython(create_default_vlan)
    ]
