# Generated by Django 2.2.4 on 2019-08-28 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATSDeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='ATS device name')),
            ],
            options={
                'db_table': 'ats_devices',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='DialLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.FloatField(unique=True, verbose_name='Unique identifier')),
                ('caller_num', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Caller number')),
                ('caller_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Caller name')),
                ('hold_time', models.PositiveSmallIntegerField(default=0, verbose_name='Hold time')),
                ('talk_time', models.PositiveSmallIntegerField(default=0, verbose_name='Talk time')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Start call time')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='End call time')),
                ('answered', models.BooleanField(default=False, verbose_name='Answered')),
                ('ats_dev', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dials.ATSDeviceModel', verbose_name='ATS device')),
            ],
            options={
                'db_table': 'dial_log',
                'ordering': ('-id',),
            },
        ),
    ]
