# Generated by Django 3.1.12 on 2021-09-14 14:31

from django.db import migrations, models
from djing2.models import BaseAbstractModelMixin
from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('groupapp', '0002_group_sites'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Title', unique=True)),
                ('sites', models.ManyToManyField(blank=True, to='sites.Site')),
            ],
            options={
                'db_table': 'locality',
            },
            bases=(BaseAbstractModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StreetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('locality', models.ForeignKey(on_delete=models.CASCADE, to='addresses.localitymodel')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
                'db_table': 'locality_street',
                'ordering': ('name',),
                "unique_together": {("name", "locality")},
            },
            bases=(BaseAbstractModelMixin, models.Model),
        ),
        migrations.RunSQL(
            sql=read_all_file('0001_initial.sql', __file__)
        )
    ]
