# Generated by Django 3.1.13 on 2021-11-17 16:18

import customer_contract.models
from django.db import migrations, models
import django.db.models.deletion
import djing2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0016_auto_20211109_1637'),
        ('profiles', '0005_auto_20210204_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_service_time', models.DateTimeField(default=customer_contract.models._datetime_now_time, verbose_name='Start service time')),
                ('end_service_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='End service time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('contract_number', models.CharField(max_length=64, unique=True, verbose_name='Contract number')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Title')),
                ('note', models.CharField(blank=True, default=None, max_length=512, null=True, verbose_name='Note')),
                ('extended_data', models.JSONField(blank=True, default=None, null=True, verbose_name='Extended data')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'db_table': 'contract',
            },
            bases=(djing2.models.BaseAbstractModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CustomerContractAttachmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('doc_file', models.FileField(max_length=128, upload_to='contract_attachments/%Y/%m/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='profiles.userprofile')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_contract.customercontractmodel')),
            ],
            options={
                'db_table': 'contract_attachment',
            },
            bases=(djing2.models.BaseAbstractModelMixin, models.Model),
        ),
    ]
