# Generated by Django 3.1.12 on 2021-07-16 21:37

from django.db import migrations, models
import django.db.models.deletion
import djing2.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210204_2043'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messenger',
        ),
        migrations.DeleteModel(
            name='ViberMessage',
        ),
        migrations.DeleteModel(
            name='ViberMessenger',
        ),
        migrations.DeleteModel(
            name='ViberSubscriber',
        ),
        migrations.CreateModel(
            name='MessengerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Description')),
                ('bot_type', models.PositiveSmallIntegerField(blank=True, choices=[], verbose_name='Bot type')),
                ('token', models.CharField(max_length=128, verbose_name='Bot secret token')),
            ],
            options={
                'verbose_name': 'Messenger',
                'verbose_name_plural': 'Messengers',
                'db_table': 'messengers',
                'ordering': ('title',),
            },
            bases=(djing2.models.BaseAbstractModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MessengerSubscriberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Name')),
                ('avatar', models.URLField(blank=True, max_length=250, null=True, verbose_name='Avatar')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='System account')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'db_table': 'messenger_subscriber',
                'ordering': ('name',),
            },
            bases=(djing2.models.BaseAbstractModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TelegramMessengerModel',
            fields=[
                ('messengermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messenger.messengermodel')),
                ('avatar', models.ImageField(null=True, upload_to='telegram_avatar', verbose_name='Avatar')),
            ],
            options={
                'db_table': 'messengers_telegram',
            },
            bases=('messenger.messengermodel',),
        ),
        migrations.CreateModel(
            name='TelegramMessengerSubscriberModel',
            fields=[
                ('messengersubscribermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messenger.messengersubscribermodel')),
                ('chat_id', models.CharField(max_length=32, verbose_name='User unique id in telegram')),
            ],
            options={
                'verbose_name': 'Telegram subscriber',
                'verbose_name_plural': 'Telegram subscribers',
                'db_table': 'messengers_telegram_subscriber',
                'ordering': ('name',),
            },
            bases=('messenger.messengersubscribermodel',),
        ),
        migrations.CreateModel(
            name='ViberMessengerModel',
            fields=[
                ('messengermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messenger.messengermodel')),
                ('avatar', models.ImageField(null=True, upload_to='viber_avatar', verbose_name='Avatar')),
            ],
            options={
                'verbose_name': 'Viber messenger',
                'verbose_name_plural': 'Viber messengers',
                'db_table': 'messengers_viber',
                'ordering': ('title',),
            },
            bases=('messenger.messengermodel',),
        ),
        migrations.CreateModel(
            name='ViberMessengerSubscriberModel',
            fields=[
                ('messengersubscribermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messenger.messengersubscribermodel')),
                ('uid', models.CharField(max_length=32, verbose_name='User unique id')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'db_table': 'messengers_viber_subscriber',
                'ordering': ('name',),
            },
            bases=('messenger.messengersubscribermodel',),
        ),
    ]
