# Generated by Django 2.2.9 on 2020-03-25 16:42

from django.db import migrations
from ._funcs import create_tbl, prepare_sql_inject


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0003_auto_20200104_1509"),
    ]

    operations = [
        migrations.RunSQL(sql=create_tbl),
        migrations.RunSQL(sql=prepare_sql_inject())
    ]
