# Generated by Django 3.0.8 on 2020-09-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_auto_20200824_1631"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ("id",),
                "permissions": [
                    ("can_remove_from_olt", "Can remove from OLT"),
                    ("can_fix_onu", "Can fix onu"),
                    ("can_apply_onu_config", "Can apply onu config"),
                ],
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.AlterModelOptions(
            name="port",
            options={
                "ordering": ("num",),
                "permissions": [("can_toggle_ports", "Can toggle ports")],
                "verbose_name": "Port",
                "verbose_name_plural": "Ports",
            },
        ),
        migrations.AlterField(
            model_name="device",
            name="code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zte_f660_bridge", "Zte ONU F660 Static Bridge"),
                    ("zte_f601_bridge", "Zte F601 dhcp"),
                    ("zte_f660_router", "Zte ONU F660 Router"),
                ],
                default=None,
                max_length=64,
                null=True,
                verbose_name="Code",
            ),
        ),
    ]
