# Generated by Django 3.0.8 on 2020-10-14 18:59

from django.db import migrations, models

from djing2.lib.for_migrations import model2default_site


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("devices", "0006_auto_20200913_0038"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="sites",
            field=models.ManyToManyField(blank=True, to="sites.Site"),
        ),
        migrations.RunPython(lambda apps, schema_editor: model2default_site(apps, schema_editor, "devices", "Device")),
    ]
