# Generated by Django 3.1.12 on 2021-08-17 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20210305_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 1, 0, 0), verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='place',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Device place address'),
        ),
        migrations.AddField(
            model_name='port',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 1, 0, 0), verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(blank=True, choices=[('zte_f601_bridge', 'Zte F601 dhcp'), ('zte_f660_bridge_d', 'Zte ONU F660 Dynamic Bridge'), ('zte_f601_static', 'Zte F601 static'), ('zte_f660_router', 'Zte ONU F660 Router'), ('zte_f660_bridge', 'Zte ONU F660 Static Bridge')], default=None, max_length=64, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unknown Device'), (1, 'DLink DGS-1100-10/ME'), (2, 'PON OLT'), (3, 'PON ONU BDCOM'), (4, 'Eltex switch'), (5, 'OLT ZTE C320'), (6, 'Zte ONU F660'), (7, 'Zte ONU F601'), (8, 'Huawei switch'), (9, 'DLink DGS-3120-24SC'), (10, 'DLink DGS-1100-06/ME'), (11, 'DLink DGS-3627G'), (12, 'Huawei switch S5300')], default=0, verbose_name='Device type'),
        ),
    ]
