# Generated by Django 2.2.4 on 2019-08-30 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("dials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DialAccount",
            fields=[
                (
                    "userprofile_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="profiles.UserProfile",
                    ),
                ),
                ("ats_number", models.PositiveSmallIntegerField(unique=True, verbose_name="ATS Number")),
            ],
            options={
                "db_table": "ats_accounts",
            },
            bases=("profiles.userprofile",),
        ),
        migrations.AddField(
            model_name="diallog",
            name="call_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Unknown"), (1, "Incoming"), (2, "Outgoing")], default=0, verbose_name="Call type"
            ),
        ),
        migrations.AddField(
            model_name="diallog",
            name="dst_caller_name",
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name="Dst caller name"),
        ),
        migrations.AddField(
            model_name="diallog",
            name="dst_caller_num",
            field=models.CharField(
                blank=True, default=None, max_length=32, null=True, verbose_name="Dst caller number"
            ),
        ),
        migrations.AddField(
            model_name="diallog",
            name="call_killer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="dials.DialAccount",
                verbose_name="Call killer",
            ),
        ),
        migrations.AddField(
            model_name="diallog",
            name="dial_account",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="dials",
                to="dials.DialAccount",
                verbose_name="Account",
            ),
        ),
    ]
