# Generated by Django 2.2.4 on 2019-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dials", "0002_auto_20190830_1816"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diallog",
            name="caller_name",
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name="Caller name"),
        ),
        migrations.AlterField(
            model_name="diallog",
            name="caller_num",
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name="Caller number"),
        ),
        migrations.AlterField(
            model_name="diallog",
            name="dst_caller_name",
            field=models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name="Dst caller name"),
        ),
        migrations.AlterField(
            model_name="diallog",
            name="dst_caller_num",
            field=models.CharField(
                blank=True, default=None, max_length=80, null=True, verbose_name="Dst caller number"
            ),
        ),
        migrations.AlterField(
            model_name="diallog",
            name="uid",
            field=models.CharField(max_length=32, unique=True, verbose_name="Unique identifier"),
        ),
    ]
