# Generated by Django 2.2.4 on 2019-09-16 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("dials", "0003_auto_20190906_1808"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSModel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("make_time", models.DateTimeField(auto_now_add=True, verbose_name="Create time")),
                ("sender", models.CharField(max_length=80, verbose_name="Sender")),
                ("receiver", models.CharField(max_length=80, verbose_name="Receiver")),
                ("text", models.CharField(max_length=280, verbose_name="Text")),
            ],
            options={
                "db_table": "dial_sms",
                "ordering": ("-id",),
            },
        ),
        migrations.RemoveField(
            model_name="diallog",
            name="dst_caller_name",
        ),
        migrations.RemoveField(
            model_name="diallog",
            name="hold_time",
        ),
        migrations.RemoveField(
            model_name="diallog",
            name="talk_time",
        ),
        migrations.AddField(
            model_name="diallog",
            name="answer_time",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Answer time"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="diallog",
            name="billsec",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Duration of the call once it was answered", verbose_name="Talk time"
            ),
        ),
        migrations.AddField(
            model_name="diallog",
            name="duration",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Duration of the call", verbose_name="Duration"
            ),
        ),
        migrations.AlterField(
            model_name="diallog",
            name="create_time",
            field=models.DateTimeField(verbose_name="Start call time"),
        ),
        migrations.AlterField(
            model_name="diallog",
            name="end_time",
            field=models.DateTimeField(auto_now=True, verbose_name="End call time"),
        ),
    ]
