# Generated by Django 2.2.1 on 2019-05-16 16:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Periodic pay name')),
                ('when_add', models.DateTimeField(auto_now_add=True, verbose_name='When pay created')),
                ('calc_type', models.PositiveSmallIntegerField(choices=[(0, 'Default periodic pay')], default=0, verbose_name='Script type for calculations')),
                ('amount', models.FloatField(verbose_name='Total amount')),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Extra info')),
            ],
            options={
                'verbose_name': 'Periodic pay',
                'verbose_name_plural': 'Periodic pays',
                'db_table': 'periodic_pay',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Service title')),
                ('descr', models.TextField(blank=True, default=None, null=True, verbose_name='Service description')),
                ('speed_in', models.FloatField(verbose_name='Speed in')),
                ('speed_out', models.FloatField(verbose_name='Speed out')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('calc_type', models.PositiveSmallIntegerField(choices=[(0, 'Base calculate functionality'), (1, 'IS'), (2, 'Private service'), (3, 'IS Daily service')], verbose_name='Script')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Tech service')),
                ('groups', models.ManyToManyField(blank=True, to='groupapp.Group', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ('title',),
                'unique_together': {('speed_in', 'speed_out', 'cost', 'calc_type')},
            },
        ),
    ]
