# Generated by Django 2.2.4 on 2019-11-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneShotPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Shot pay name')),
                ('cost', models.FloatField(verbose_name='Total cost')),
                ('pay_type', models.PositiveSmallIntegerField(choices=[(0, 'Default shot pay logic')], default=0, help_text='Uses for callbacks before pay and after pay', verbose_name='One shot pay type')),
            ],
            options={
                'db_table': 'service_one_shot',
                'ordering': ('name',),
            },
        ),
    ]
