# Generated by Django 3.1.7 on 2021-03-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicpay',
            name='extra_info',
            field=models.JSONField(blank=True, null=True, verbose_name='Extra info'),
        ),
    ]
