# Generated by Django 3.1.12 on 2021-06-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0008_change_find_customer_service_by_device_credentials_fn'),
        ('profiles', '0005_auto_20210204_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Comment time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Author')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'db_table': 'customer_comments',
            },
        ),
    ]
