# Generated by Django 3.0.7 on 2020-06-29 18:34
import re
from django.db import migrations, models
from django.core.validators import RegexValidator
from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ("networks", "0005_networkippool_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkippool",
            name="pool_tag",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=32,
                null=True,
                validators=[
                    RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
                verbose_name="Tag",
            ),
        ),
        migrations.RunSQL(sql=read_all_file("0006_change_fetch_subscriber_lease.sql", __file__)),
    ]
