# Generated by Django 3.0.8 on 2020-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("networks", "0008_auto_20201105_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkippool",
            name="sites",
            field=models.ManyToManyField(blank=True, to="sites.Site"),
        ),
        migrations.AddField(
            model_name="vlanif",
            name="sites",
            field=models.ManyToManyField(blank=True, to="sites.Site"),
        ),
    ]
