# Generated by Django 3.1.12 on 2021-08-20 14:10

import datetime
from django.db import migrations, models
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0014_update_find_new_ip_pool_lease_fn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkippool',
            name='pool_tag',
        ),
        migrations.AddField(
            model_name='networkippool',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networkippool',
            name='network',
            field=netfields.fields.CidrAddressField(help_text='Ip address of network. For example: 192.168.1.0/24 or fde8:6789:1234:1::/64', max_length=43, unique=True, verbose_name='Ip network address'),
        ),
    ]
