# Generated by Django 3.1.13 on 2022-01-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0015_auto_20210820_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeripleasemodel',
            options={'verbose_name': 'IP lease', 'verbose_name_plural': 'IP leases'},
        ),
        migrations.AlterModelOptions(
            name='networkippool',
            options={'verbose_name': 'Network ip pool', 'verbose_name_plural': 'Network ip pools'},
        ),
        migrations.AlterModelOptions(
            name='vlanif',
            options={'verbose_name': 'Vlan', 'verbose_name_plural': 'Vlan list'},
        ),
        migrations.AlterField(
            model_name='customeripleasemodel',
            name='pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.networkippool'),
        ),
    ]
