# Generated by Django 3.1.14 on 2022-05-26 13:47

from datetime import datetime
from django.db import migrations, models
from django.db.models import deletion
from networks.models import NetworkIpPool


def _fill_pool_lease_reserve(apps, schema_editor):
    #  ip_pool_model = apps.get_model('networks', 'NetworkIpPool')
    for pool in NetworkIpPool.objects.iterator():
        pool.reserve_leases()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_auto_20220526_1347'),
        ('networks', '0017_auto_20220425_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeripleasemodel',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=deletion.SET_NULL, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='customeripleasemodel',
            name='lease_time',
            field=models.DateTimeField(blank=True, default=datetime.now, null=True, verbose_name='Lease time'),
        ),
        migrations.RunSQL(
            sql="DROP FUNCTION IF EXISTS find_new_ip_pool_lease(varchar, boolean, smallint, smallint)"
        ),
        migrations.RunSQL(
            sql="DROP FUNCTION IF EXISTS create_lease_w_auto_pool(inet, macaddr, int, varchar, uuid, smallint, smallint)"
        ),
        migrations.RunPython(_fill_pool_lease_reserve)
    ]
