# Generated by Django 3.1.14 on 2022-05-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_auto_20220526_1347'),
        ('networks', '0017_auto_20220425_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeripleasemodel',
            name='customer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer'),
        ),
    ]
