# Generated by Django 2.2.1 on 2019-06-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateway',
            old_name='default',
            new_name='is_default',
        ),
    ]
