# Generated by Django 3.0.8 on 2020-11-25 17:50

from django.db import migrations
from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0003_auto_20201014_1859'),
    ]

    operations = [
        migrations.RunSQL(
            sql=read_all_file('0004_fetch_credentials_params.sql', __file__),
            reverse_sql="DROP FUNCTION IF EXISTS fetch_customers_srvnet_credentials_by_gw;"
        )
    ]
