# Generated by Django 3.1.14 on 2022-02-23 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0005_auto_20210204_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='HookObserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Model Post Save'), (2, 'Model Post Delete'), (3, 'Model Pre Save'), (4, 'Model Pre Delete')], default=0, verbose_name='Notification type')),
                ('client_url', models.URLField(verbose_name='Client url')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile', verbose_name='Subscription profile')),
            ],
            options={
                'db_table': 'hook_observer',
                'unique_together': {('notification_type', 'client_url', 'content_type')},
            },
        ),
    ]
