# Generated by Django 2.2 on 2020-06-02 16:21

from django.db import migrations
from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ("gateways", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=read_all_file("0002_fetch_credentials.sql", __file__),
            reverse_sql="DROP FUNCTION IF EXISTS fetch_customers_srvnet_credentials_by_gw;",
        )
    ]
