# Generated by Django 3.1.12 on 2021-08-25 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0004_fetch_credentials_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 1, 0, 0), verbose_name='Create time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gateway',
            name='gw_class',
            field=models.PositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'sgsn'), (2, 'ggsn'), (3, 'smsc'), (4, 'gmsc'), (5, 'hss'), (6, 'pstn'), (7, 'voip-gw'), (8, 'aaa'), (9, 'nat')], default=0, verbose_name='Gateway class'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='place',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Device place address'),
        ),
    ]
