# Generated by Django 3.1.14 on 2022-11-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateways', '0005_auto_20210825_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gateway',
            options={
                'verbose_name': 'Network access server. Gateway',
                'verbose_name_plural': 'Network access servers. Gateways'
            },
        ),
        migrations.RunSQL(
            sql="DROP FUNCTION fetch_customers_srvnet_credentials_by_gw"
        ),
    ]
