# Generated by Django 3.1.13 on 2022-01-06 16:22

from django.db import migrations, models
from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('radiusapp', '0002_auto_20210219_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerradiussession',
            name='session_duration',
            field=models.DurationField(blank=True, default=None, help_text='most often this is Acct-Session-Time av pair', null=True, verbose_name='Session duration'),
        ),
        migrations.RunSQL(sql=read_all_file("0003_auto_20220106_1622.sql", __file__)),
    ]
