# Generated by Django 3.1.14 on 2022-04-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiusapp', '0003_auto_20220106_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRadiusSession',
        ),
    ]
