# Generated by Django 3.0.8 on 2021-01-08 18:19

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_find_customer_service_by_device_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaltelephone',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime(1970, 1, 1, 3, 0)),
            preserve_default=False,
        ),
    ]
