# Generated by Django 3.0.8 on 2021-02-22 14:10
from django.db import migrations
from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_passportinfo_division_code'),
    ]

    operations = [
        migrations.RunSQL(
            sql=read_all_file('0008_change_find_customer_service_by_device_credentials_fn.sql', __file__)
        )
    ]
