# Generated by Django 2.2.9 on 2020-05-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('tasks', '0002_auto_20200412_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDocumentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('doc_file', models.FileField(max_length=128, upload_to='task_attachments/%Y/%m/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'db_table': 'task_doc_attachments',
            },
        ),
    ]
