# Generated by Django 2.2.4 on 2019-08-19 15:14

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayAllTimeGateway",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=64, verbose_name="Title")),
                ("secret", encrypted_model_fields.fields.EncryptedCharField(verbose_name="Secret")),
                ("service_id", models.CharField(max_length=64, verbose_name="Service id")),
                ("slug", models.SlugField(max_length=32, unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "All time gateway",
                "db_table": "pay_all_time_gateways",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="AllTimePayLog",
            fields=[
                ("pay_id", models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("sum", models.FloatField(default=0.0, verbose_name="Cost")),
                (
                    "trade_point",
                    models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name="Trade point"),
                ),
                ("receipt_num", models.BigIntegerField(default=0, verbose_name="Receipt number")),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="customers.Customer",
                    ),
                ),
                (
                    "pay_gw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fin_app.PayAllTimeGateway",
                        verbose_name="Pay gateway",
                    ),
                ),
            ],
            options={
                "db_table": "all_time_pay_log",
                "ordering": ("-date_add",),
            },
        ),
    ]
