# Generated by Django 3.1.14 on 2022-06-02 16:50

from django.db import migrations, models
import django.db.models.deletion
import djing2.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('customers', '0018_auto_20220120_1704'),
        ('fin_app', '0002_payalltimegateway_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRNCBGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='Slug')),
                ('sites', models.ManyToManyField(blank=True, to='sites.Site')),
            ],
            options={
                'verbose_name': 'RNCB gateway',
                'db_table': 'pay_rncb_gateways',
            },
            bases=(djing2.models.BaseAbstractModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='alltimepaylog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payalltimegateway',
            options={'verbose_name': 'All time gateway'},
        ),
        migrations.CreateModel(
            name='RNCBPayLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_id', models.IntegerField(unique=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('acct_time', models.DateTimeField(verbose_name='Act time from payment system')),
                ('amount', models.DecimalField(decimal_places=6, default=0.0, max_digits=19, verbose_name='Cost')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='customers.customer')),
                ('pay_gw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fin_app.payrncbgateway', verbose_name='Pay gateway')),
            ],
            options={
                'db_table': 'rncb_pay_log',
            },
            bases=(djing2.models.BaseAbstractModelMixin, models.Model),
        ),
    ]
