# Generated by Django 3.1.14 on 2022-07-18 12:08

from django.db import migrations, models


def _copy_field(apps, schema_editor):
    alltimepaylog = apps.get_model('fin_app', 'AllTimePayLog')
    alltimepaylog.objects.update(
        amount=models.F('sum')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app', '0003_auto_20220602_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltimepaylog',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=19, verbose_name='Cost'),
        ),
        migrations.RunPython(_copy_field),
        migrations.RemoveField(
            model_name='alltimepaylog',
            name='sum',
        ),
    ]
