# Generated by Django 2.2.3 on 2019-07-23 02:20

from django.db import migrations, models
import networks.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', networks.fields.GenericIpAddressWithPrefix(help_text='Ip address of network. For example: 192.168.1.0 or fde8:6789:1234:1::', unique=True, verbose_name='IP network')),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, 'Not defined'), (1, 'Internet'), (2, 'Guest'), (3, 'Trusted'), (4, 'Devices'), (5, 'Admin')], default=0, verbose_name='Kind of network')),
                ('description', models.CharField(max_length=64, verbose_name='Description')),
                ('ip_start', models.GenericIPAddressField(verbose_name='Start work ip range')),
                ('ip_end', models.GenericIPAddressField(verbose_name='End work ip range')),
                ('groups', models.ManyToManyField(to='groupapp.Group', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
                'db_table': 'networks_network',
                'ordering': ('network',),
            },
        ),
    ]
