# Generated by Django 2.2.5 on 2019-12-18 19:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VlanIf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Vlan interface')),
                ('vid', models.PositiveSmallIntegerField(default=1, unique=True, validators=[
                    django.core.validators.MinLengthValidator(2, message='Vid could not be less then 2'),
                    django.core.validators.MaxValueValidator(4094, message='Vid could not be more than 4094')
                ], verbose_name='VID')),
                ('is_management', models.BooleanField(default=False, verbose_name='Is management')),
            ],
            options={
                'verbose_name': 'Vlan',
                'verbose_name_plural': 'Vlan list',
                'db_table': 'networks_vlan',
            },
        ),
        migrations.AlterModelOptions(
            name='networkmodel',
            options={'verbose_name': 'Network', 'verbose_name_plural': 'Networks'},
        ),
        migrations.AddField(
            model_name='networkmodel',
            name='vlan_if',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.VlanIf', verbose_name='Vlan interface'),
        ),
    ]
