# Generated by Django 2.2.4 on 2020-03-13 11:58
import os
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import netfields.fields


def _real_all(fname):
    curr_dir = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(curr_dir, fname), 'r') as f:
        data = f.read(0xffff)
    return data


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200313_1158'),
        ('networks', '0002_auto_20191218_1907'),
    ]

    operations = [
        migrations.RunSQL(
            sql=_real_all('0003_radius_integration.sql'),
            state_operations=[
                migrations.CreateModel(
                    name='CustomerIpLease',
                    fields=[
                        ('id',
                         models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('ip_address', models.GenericIPAddressField(verbose_name='Ip address')),
                        ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='networks.NetworkIpPool')),
                        ('lease_time', models.DateTimeField(auto_now_add=True, verbose_name='Lease time')),
                        ('customer_mac', netfields.fields.MACAddressField(verbose_name='Customer mac address')),
                        ('customer',
                         models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                    ],
                    options={
                        'verbose_name': 'Customer ip lease',
                        'verbose_name_plural': 'Customer ip leases',
                        'db_table': 'networks_ip_leases',
                    },
                ),
                migrations.CreateModel(
                    name='NetworkIpPool',
                    fields=[
                        ('id',
                         models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('network', models.GenericIPAddressField(
                            help_text='Ip address of network. For example: 192.168.1.0 or fde8:6789:1234:1::',
                            unique=True, verbose_name='Ip network address')),
                        ('net_mask', models.PositiveSmallIntegerField(default=24, verbose_name='Network mask')),
                        ('kind', models.PositiveSmallIntegerField(
                            choices=[(0, 'Not defined'), (1, 'Internet'), (2, 'Guest'), (3, 'Trusted'), (4, 'Devices'),
                                     (5, 'Admin')], default=0, verbose_name='Kind of network')),
                        ('description', models.CharField(max_length=64, verbose_name='Description')),
                        ('ip_start', models.GenericIPAddressField(verbose_name='Start work ip range')),
                        ('ip_end', models.GenericIPAddressField(verbose_name='End work ip range')),
                        ('vlan_if', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='networks.VlanIf', verbose_name='Vlan interface')),
                        ('gateway', models.GenericIPAddressField(verbose_name='Gateway ip address')),
                        ('lease_time', models.PositiveSmallIntegerField(default=3600, verbose_name='Lease time seconds')),
                    ],
                    options={
                        'verbose_name': 'Network ip pool',
                        'verbose_name_plural': 'Network ip pools',
                        'db_table': 'networks_ip_pool',
                        'ordering': ('network',),
                    },
                ),
            ]
        ),
        migrations.AlterModelOptions(
            name='vlanif',
            options={'ordering': ('-id',), 'verbose_name': 'Vlan', 'verbose_name_plural': 'Vlan list'},
        ),
        migrations.AlterField(
            model_name='vlanif',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Vlan title'),
        ),
        migrations.AlterField(
            model_name='vlanif',
            name='vid',
            field=models.PositiveSmallIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(2, message='Vid could not be less then 2'), django.core.validators.MaxValueValidator(4094, message='Vid could not be more than 4094')], verbose_name='VID'),
        ),
        migrations.DeleteModel(
            name='NetworkModel',
        )
    ]
