# Generated by Django 2.2.9 on 2020-04-25 14:22

from django.db import migrations, models

from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_radius_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkippool',
            name='is_dynamic',
            field=models.BooleanField(default=False, verbose_name='Is dynamic'),
        ),
        migrations.RunSQL(
            sql=read_all_file('0004_networkippool_is_dynamic.sql', __file__)
        )
    ]
