# Generated by Django 3.0.8 on 2020-10-14 18:59

from django.db import migrations, models

from djing2.lib.for_migrations import model2default_site


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('networks', '0007_signal_from_external_dhcp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeripleasemodel',
            options={'ordering': ('id',), 'verbose_name': 'IP lease', 'verbose_name_plural': 'IP leases'},
        ),
        migrations.AlterModelOptions(
            name='vlanif',
            options={'ordering': ('vid',), 'verbose_name': 'Vlan', 'verbose_name_plural': 'Vlan list'},
        ),
        migrations.AddField(
            model_name='networkippool',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='vlanif',
            name='sites',
            field=models.ManyToManyField(blank=True, to='sites.Site'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: model2default_site(apps, schema_editor, 'networks', 'VlanIf')
        ),
        migrations.RunPython(
            lambda apps, schema_editor: model2default_site(apps, schema_editor, 'networks', 'NetworkIpPool')
        ),
    ]
