# Generated by Django 3.0.8 on 2020-11-30 17:15

from django.db import migrations
from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0009_auto_20201109_1437'),
    ]

    operations = [
        migrations.RunSQL(
            sql=read_all_file('0010_find_service_permit_updated.sql', __file__)
        ),
    ]
