# Generated by Django 3.0.8 on 2021-01-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0010_find_service_permit_updated'),
    ]

    operations = [
        # Add index to network_ip_leases
        migrations.RunSQL(
            sql="CREATE INDEX networks_ip_leases_ip_index ON networks_ip_leases USING GIST(ip_address inet_ops);"
        )
    ]
