# Generated by Django 3.0.8 on 2021-02-11 16:25

from django.db import migrations, models
import django.db.models.deletion
import netfields.fields

from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_passportinfo_division_code'),
        ('networks', '0011_ip_addr_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIpLeaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Ip address')),
                ('lease_time', models.DateTimeField(auto_now_add=True, verbose_name='Lease time')),
                ('last_update', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last update')),
                ('mac_address', netfields.fields.MACAddressField(default=None, null=True, verbose_name='Mac address')),
                ('is_dynamic', models.BooleanField(default=False, verbose_name='Is synamic')),
                ('event_time', models.DateTimeField(auto_now_add=True, verbose_name='Event time')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
            ],
            options={
                'db_table': 'networks_ip_lease_log',
            },
        ),
        migrations.RunSQL(sql=read_all_file('0012_customeripleaselog.sql', __file__))
    ]
