# Generated by Django 3.0.8 on 2021-02-18 13:00

from django.db import migrations, models
from django.db.models.deletion import CASCADE
from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_change_find_customer_service_by_device_credentials_fn'),
        ('networks', '0012_customeripleaselog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeripleasemodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=CASCADE, to='customers.Customer'),
        ),
        migrations.RunSQL(sql=read_all_file('0013_update_find_new_ip_pool_lease_fn.sql', __file__))
    ]
