# Generated by Django 3.0.8 on 2021-02-18 13:00

from django.db import migrations

from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0012_customeripleaselog'),
    ]

    operations = [
        migrations.RunSQL(sql=read_all_file('0013_update_find_new_ip_pool_lease_fn.sql', __file__))
    ]
