# Generated by Django 3.0.8 on 2020-10-25 15:45

from django.db import migrations, models
import django.db.models.deletion
import djing2.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200723_1633'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViberMessage',
        ),
        migrations.DeleteModel(
            name='ViberMessenger',
        ),
        migrations.DeleteModel(
            name='ViberSubscriber',
        ),
        migrations.CreateModel(
            name='MessengerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(verbose_name='Message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('sender', models.CharField(max_length=32, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messenger_messages',
                'ordering': ('-date',),
            },
            bases=(djing2.models.BaseAbstractModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MessengerSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, verbose_name='User unique id')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Name')),
                ('avatar', models.URLField(blank=True, max_length=250, null=True, verbose_name='Avatar')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile', verbose_name='System account')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'db_table': 'messenger_subscriber',
                'ordering': ('name',),
            },
            bases=(djing2.models.BaseAbstractModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='messenger',
            name='avatar',
            field=models.ImageField(null=True, upload_to='messenger_avatar', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='messenger',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='messenger',
            name='token',
            field=models.CharField(default='', max_length=128, verbose_name='Bot secret token'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messenger',
            name='bot_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Viber'), (2, 'Telegram')], verbose_name='Bot type'),
        ),
        migrations.AddField(
            model_name='messengermessage',
            name='messenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Messenger', verbose_name='Messenger'),
        ),
        migrations.AddField(
            model_name='messengermessage',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messenger.MessengerSubscriber', verbose_name='Subscriber'),
        ),
    ]
