# Generated by Django 3.1.7 on 2021-06-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0002_group_sites'),
        ('sorm_export', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiasrecursiveaddressmodel',
            name='groups'
        ),
        migrations.AddField(
            model_name='fiasrecursiveaddressmodel',
            name='groups',
            field=models.ManyToManyField(to='groupapp.Group')
        ),
        migrations.DeleteModel(
            name='FiasAddrGroupModel',
        ),
        migrations.RunSQL(
            sql="create unique index if not exists sorm_address_groups_groupid_uniq "
                "on sorm_address_groups (group_id);",
            reverse_sql="drop index if exists sorm_address_groups_groupid_uniq;"
        )
    ]
