# Generated by Django 3.1.7 on 2021-06-09 15:11

from django.db import migrations, models
from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):

    dependencies = [
        ('groupapp', '0002_group_sites'),
        ('sorm_export', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiasrecursiveaddressmodel',
            name='groups'
        ),
        migrations.AddField(
            model_name='fiasrecursiveaddressmodel',
            name='groups',
            field=models.ManyToManyField(to='groupapp.Group', blank=True)
        ),
        migrations.DeleteModel(
            name='FiasAddrGroupModel',
        ),
        migrations.AlterField(
            model_name='exportstampmodel',
            name='data',
            field=models.JSONField(verbose_name='Export event data'),
        ),
        migrations.RunSQL(
            sql=read_all_file("0002_auto_20210609_1511.py.sql", __file__),
            reverse_sql="ALTER TABLE sorm_address_groups drop CONSTRAINT "
                        "sorm_address_groups_groupsid_uniq;"
                        "DROP VIEW get_streets_as_addr_objects;"
        ),
    ]
