# Generated by Django 3.1.12 on 2021-09-14 18:03

from django.db import migrations, models

from djing2.lib.for_migrations import read_all_file


class Migration(migrations.Migration):
    dependencies = [
        ('addresses', '0001_initial'),
        ('sorm_export', '0002_auto_20210609_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiasrecursiveaddressmodel',
            name='groups',
        ),
        migrations.AddField(
            model_name='fiasrecursiveaddressmodel',
            name='localities',
            field=models.ManyToManyField(blank=True, to='addresses.LocalityModel'),
        ),
        migrations.RunSQL(
            sql=read_all_file("0003_auto_20210914_1803.sql", __file__)
        )
    ]
