# Generated by Django 3.1.12 on 2021-09-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('addresses', '0001_initial'),
        ('sorm_export', '0002_auto_20210609_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiasrecursiveaddressmodel',
            name='locality',
            field=models.OneToOneField(to='addresses.LocalityModel', on_delete=models.deletion.CASCADE,
                                       null=True, blank=True, default=None),
        ),
        migrations.RunSQL(
            sql="drop view if exists get_streets_as_addr_objects;"
        ),
        migrations.RemoveField(
            model_name='fiasrecursiveaddressmodel',
            name='groups',
        ),
    ]
