# Generated by Django 3.1.14 on 2022-12-15 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorm_export', '0003_auto_20220822_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^(\\+[7893]\\d{10,11})?$')], verbose_name='Telephone')),
                ('actual_begin_datetime', models.DateTimeField()),
                ('actual_end_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'sorm_special_numbers',
            },
        ),
    ]
