# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Sphinx to GitHub Pages'
description: 'GitHub Action to deploy Sphinx documentation to GitHub Pages'
inputs:
  target_branch:
    description: 'Git branch where assets will be deployed'
    required: false
    default: 'gh-pages'
  repository_path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: false
    default: '.'
  documentation_path:
    description: 'Relative path under repository to documentation source files'
    required: false
    default: '.'
  install_requirements:
    description: 'Install Sphinx extensions listed in $documentation_path/requirements.txt'
    required: false
    default: 'true'
  extra_files:
    description: 'Extras files(such as README, LICENSE) to be commited to $target_branch'
    required: false
    default: ''

runs:
  using: 'bash'
  main: 'make html'
