# Generated by Django 2.2.5 on 2019-10-23 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatCache',
            fields=[
                ('last_time', models.IntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='customers.Customer')),
                ('octets', models.PositiveIntegerField(default=0)),
                ('packets', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'flowcache',
                'ordering': ('-last_time',)
            },
        ),
    ]
