name: Run test on push

on:
  push:
    branches:
      - devel
      - master
      - env_config
jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    env:
      APP_DEBUG: y
      ALLOWED_HOSTS: '127.0.0.1|localhost'
      DEFAULT_EMAIL: nerosketch@gmail.com
      ADMINS: '[["Dmitry Novikov", "nerosketch@gmail.com"]]'
      POSTGRES_DB: djing2
      POSTGRES_USER: djing2_usr
      POSTGRES_HOST: postgres
      API_AUTH_SUBNET: '127.0.0.0/8'
      MESSENGER_BOT_PUBLIC_URL: 'http://localhost'
      ARPING_ENABLED: y
      ARPING_COMMAND: echo
      SORM_EXPORT_FTP_HOST: localhost
      SORM_EXPORT_FTP_USERNAME: cdr
      SORM_EXPORT_FTP_DISABLE: y
      RADIUS_APP_HOST: localhost

    steps:
        # Чекаутим код
      - uses: actions/checkout@master
      - name: Make secrets
        run: mkdir -p secrets \
          && openssl rand -base64 20 > ./secrets/API_AUTH_SECRET \
          && openssl rand -base64 50 > ./secrets/DJANGO_SECRET_KEY \
          && openssl rand -base64 32 > ./secrets/FIELD_ENCRYPTION_KEY \
          && openssl rand -base64 20 > ./secrets/RADIUS_APP_SECRET \
          && openssl rand -base64 20 > ./secrets/SORM_EXPORT_FTP_PASSWORD \
          && openssl rand -base64 20 > ./secrets/VAPID_PUBLIC_KEY \
          && openssl rand -base64 20 > ./secrets/VAPID_PRIVATE_KEY \
          && openssl rand -base64 20 > ./secrets/POSTGRES_PASSWORD \
          && openssl rand -base64 20 > ./secrets/RADIUS_SECRET
      - name: Build docker containers
        run: docker-compose build
      - name: Run tests
        run: docker exec djing2_app ./manage.py test
