name: Run test on push

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - devel
      - master
      - env_config
jobs:
  run_tests:
    runs-on: [ubuntu-latest]

    env:
      SECRETS_DIR_PATH: /run/secrets
      ALLOWED_HOSTS: '127.0.0.1 localhost'
      DEFAULT_EMAIL: nerosketch@gmail.com
      ADMINS: '[["Dmitry Novikov", "nerosketch@gmail.com"]]'
      POSTGRES_DB: djing2
      POSTGRES_USER: djing2_usr
      POSTGRES_HOST: localhost
      API_AUTH_SUBNET: '127.0.0.0/8'
      MESSENGER_BOT_PUBLIC_URL: 'http://localhost'
      ARPING_ENABLED: y
      SORM_EXPORT_FTP_HOST: localhost
      SORM_EXPORT_FTP_USERNAME: cdr
      RADIUS_APP_HOST: password

    steps:
        # Чекаутим код
      - uses: actions/checkout@master
        # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install os requirements
        run: sudo apt-get install -y libmemcached-dev python3-psycopg2 postgresql-server-dev-12 libsnmp-dev
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        #run: coverage run src/tests.py
        run: ./manage.py test
