name: Run test on push

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - devel
      - master
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
        # Чекаутим код
      - uses: actions/checkout@master
        # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install os requirements
        run: sudo apt-get install -y libmemcached-dev python3-psycopg2 postgresql-server-dev-12 libsnmp-dev
      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt
      - name: Run tests
        #run: coverage run src/tests.py
        run: manage.py test
