# Generated by Django 3.1.12 on 2021-09-08 13:18

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ('dynamicfields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmodel',
            name='system_tag',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Default tag'), (1, 'Uses IPTV')], default=0,
                                                   verbose_name='System tag'),
        ),
        migrations.AddField(
            model_name='fieldmodel',
            name='user_tag',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, validators=[
                django.core.validators.RegexValidator(re.compile('^(\\w+\\,?)+$'),
                                                      'Tags must contain only word characters (equivalent to [a-zA-Z0-9_]). And separated by comma.',
                                                      'invalid')], verbose_name='User tag'),
        ),
    ]
