# Generated by Django 3.1.13 on 2021-11-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicfields', '0002_tags_20210908_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='fieldmodel',
            name='field_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Char Field'), (1, 'Integer Field'), (2, 'Email Field'), (3, 'Ip Field'), (4, 'Float Field'), (5, 'Slug Field'), (6, 'Datetime field'), (7, 'Boolean field')], default=0, verbose_name='Field type'),
        ),
    ]
